spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:11521/ORCL
    username: cmsmp
    password: cmsmp
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 1000
  application:
    name: cmsmpwx
  batch:
    job:
      enabled: false
logging:
  level:
    root: info
    com.example.zhouyunlong.pintuan: debug
    com.example.zhouyunlong.pintuan.dao: trace


mybatis:
  mapper-locations: classpath:/mapper/**.xml
  typeAliasesPackage: com.example.zhouyunlong.pintuan.entity,com.example.zhouyunlong.pintuan.domain
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    # Sequence序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #驼峰下划线转换
    db-column-underline: true
    #数据库大写下划线转换
    capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6379
server:
  port: 8099

wx:
  miniapp:
    configs:
      - appid: wx9e21023282f95ec6 #微信小程序的appid,龙粉人气榜
        secret: 8482a8aacf4adb45a7a524ac1455794e #微信小程序的Secret
        token: longzhifu #微信小程序消息服务器配置的token
        aesKey: WUJz11LvaL23C6OaPoSiHzByGs7YVC7Gz13YpAfaMQJ #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka/
ribbon:
  eureka:
    enabled: true